AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: graphql.lambda_handler
      Runtime: nodejs8.10
      Description: GraphQL example function
      MemorySize: 128
      Timeout: 15
      Events:
        GraphQLAPI:
          Type: Api
          Properties:
            Path: /graphql
            Method: Any
  GraphQLTestTable: 
    Type: AWS::Serverless::SimpleTable
    Properties: 
      PrimaryKey: 
        Name: timestamp
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
